//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.81.0.
// 
namespace Syndaryl.TreasureGenerator {
    using System;
    using System.Collections.Generic;
    using System.Xml.Serialization;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class df8 {
        
        private df8Category[] categoryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("category")]
        public df8Category[] category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class df8Category {
        
        private df8CategoryItem[] itemField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("item")]
        public df8CategoryItem[] item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class df8CategoryItem {
        
        private object[] itemsField;
        
        private ItemsChoiceType[] itemsElementNameField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Attribute", typeof(df8CategoryItemAttribute))]
        [System.Xml.Serialization.XmlElementAttribute("CF", typeof(decimal))]
        [System.Xml.Serialization.XmlElementAttribute("Capacity", typeof(decimal))]
        [System.Xml.Serialization.XmlElementAttribute("ContainmentType", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("Cost", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("Description", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("RandomWeight", typeof(decimal))]
        [System.Xml.Serialization.XmlElementAttribute("Reroll", typeof(df8CategoryItemReroll))]
        [System.Xml.Serialization.XmlElementAttribute("Reserve", typeof(byte))]
        [System.Xml.Serialization.XmlElementAttribute("TehKey", typeof(ushort))]
        [System.Xml.Serialization.XmlElementAttribute("Type", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("Unit", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("UnitPrice", typeof(decimal))]
        [System.Xml.Serialization.XmlElementAttribute("ValidForAttribute", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("WF", typeof(sbyte))]
        [System.Xml.Serialization.XmlElementAttribute("Weight", typeof(decimal))]
        [System.Xml.Serialization.XmlElementAttribute("motif", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType[] ItemsElementName {
            get {
                return this.itemsElementNameField;
            }
            set {
                this.itemsElementNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class df8CategoryItemAttribute {
        
        private string nameField;
        
        private string valueField;
        
        private string operationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string operation {
            get {
                return this.operationField;
            }
            set {
                this.operationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class df8CategoryItemReroll {
        
        private string categoryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
    public enum ItemsChoiceType {
        
        /// <remarks/>
        Attribute,
        
        /// <remarks/>
        CF,
        
        /// <remarks/>
        Capacity,
        
        /// <remarks/>
        ContainmentType,
        
        /// <remarks/>
        Cost,
        
        /// <remarks/>
        Description,
        
        /// <remarks/>
        RandomWeight,
        
        /// <remarks/>
        Reroll,
        
        /// <remarks/>
        Reserve,
        
        /// <remarks/>
        TehKey,
        
        /// <remarks/>
        Type,
        
        /// <remarks/>
        Unit,
        
        /// <remarks/>
        UnitPrice,
        
        /// <remarks/>
        ValidForAttribute,
        
        /// <remarks/>
        WF,
        
        /// <remarks/>
        Weight,
        
        /// <remarks/>
        motif,
    }
}
